class Exception {
    // eslint-disable-next-line no-restricted-syntax
    constructor(code, message) {
        this.retcode = code;
        this.retmsg = message;
    }
}

const ErrCode = {
    ERRCODE_INTERNAL_ERROR: 100000,
    ERRCODE_PATH_NOT_FOUND: 100001,
    ERRCODE_REQ_PARAM: 100004,
    ERRCODE_CAPTCHA_WRONG: 100005,
    ERRCODE_CAPTCHA_NEED: 100006,
    ERRCODE_ILLEGAL_ACCESS: 100007,
    ERRCODE_TOKEN_EXPIRED: 100008,
    ERRCODE_ILLEGAL_ACCESS_SIGN_DATE: 100009,
    ERRCODE_CALL_API_REPEAT: 100010,
    ERRCODE_TOKEN_NOT_VALIDATE: 100011,
    ERRCODE_ACCOUNT_NEED_LOGOUT: 100014,
    ERRCODE_PURCHASE_VALIDATE_UNKNOWN_ERROR: 100007,

    // 20
    ERRCODE_MAX_TRIES: 200002,
    ERRCODE_MAX_TRIES_IP: 200005,
    ERRCODE_MAX_BONUS_PER_DAY: 200006,
    ERRCODE_MAX_BONUS_PER_HOUR: 200007,
    ERRCODE_CHECK_IN_REPEAT: 200009,
    ERRCODE_SET_PHONE_FAILED: 200011,
    ERRCODE_CANCEL_MEMBERSHIP_FAILED: 200012,
    ERRCODE_RESTORE_MEMBERSHIP_FAILED: 200013,
    ERRCODE_PRODUCT_NOT_FOUND: 200014,
    ERRCODE_RECHARGE_AMOUNT_NOT_MATCH: 200015,
    ERRCODE_ACCOUNT_BLOCKED: 200017,
    ERRCODE_NO_SUCH_ACCOUNT: 200018,
    ERRCODE_ACCOUNT_HAVE_MEMBERSHIP: 200019,
    ERRCODE_CODE_ERROR: 200020,
    ERRCODE_TRANSACTION_NOT_FOUND: 200021,
    ERRCODE_TRANSACTION_STATE_ALREADY: 200022,
    ERRCODE_ACCOUNT_NOT_MEMBERSHIP: 200023,
    ERRCODE_TRANSACTION_RECHARGE_ERROR: 200024,
    ERRCODE_PURCHASE_MAX_LIMIT: 200025,
    ERRCODE_TRANSACTION_ALREADY_PROCESSED: 200026,
    ERRCODE_PURCHASE_VALIDATE_FAILED: 200027,
    ERRCODE_INVITE_CODE_ERROR: 200028,
    ERRCODE_SET_INVITE_CODE_FAILED: 200029,
    ERRCODE_SET_INVITE_CODE_FULL: 200030,
    ERRCODE_SET_INVITE_CODE_DEVICE_DUP: 200031,
    ERRCODE_INVITE_LOWEST_VERSION: 200032,
    ERRCODE_SET_PHONE_FAILED_TIP: 200037,
    ERRCODE_PURCHASE_MAX_TIMES_LIMIT: 200048,
    ERRCODE_ACCOUNT_DEACTIVATED: 200049,
    ERRCODE_PHONE_EXIST: 210001,
    ERRCODE_PHONE_NOT_EXIST: 210002,

    // crypto
    ERRCODE_CRYPTO_PAY_SUBMIT_ERROR: 200101,

    ERRCODE_TRANSACTION_AVS_VERIFY_ERROR: 200050,
    ERRCODE_TRANSACTION_CVV2_VERIFY_ERROR: 200051,
    ERRCODE_TRANSACTION_VERIFY_ERROR: 200052,

    // call
    ERRCODE_CALL_INCORRECT_NUMBER: 300000,
    ERRCODE_VALIDATE_METHOD_SMS: 300001,
    ERRCODE_CALL_NOT_ENOUGH_BALANCE: 300002,
    ERRCODE_CALL_NOT_SUPPORT_NUMBER: 300004,
    ERRCODE_SMS_NOT_SUPPORT_TOLLFREE: 300005,
    ERRCODE_SMS_SENT_LIMIT: 300006,
    ERRCODE_SMS_INCORRECT_FROM_NUMBER: 300007,
    ERRCODE_SMS_INCORRECT_NUMBER: 300008,
    ERRCODE_SMS_ACCOUNT_LOG_OUT: 300009,
    ERRCODE_SMS_SIMILAR_LIMIT2: 300010,
    ERRCODE_SMS_SIMILAR_LIMIT: 300011,
    ERRCODE_SMS_NOT_SUPPORT_UK: 300012,
    ERRCODE_SMS_SEND_FAILED: 300013,
    ERRCODE_SMS_TOLLFREE_NOT_OPENED: 300014,
    ERRCODE_CALL_INCORRECT_CHINA_NUMBER: 300020,
    ERRCODE_CALL_CALLER_NUMBER_EXPIRED: 300021,
    ERRCODE_CALL_HIGH_FREQ_LIMIT: 300022,
    ERRCODE_CALL_WATCH_AD_LIMIT: 300024,
    ERRCODE_CALL_HIGHRATE_BALANCE_NOT_ENOUGH: 300025,

    // sub
    ERRCODE_SUB_VIRTUAL_PHONE_FAILED: 400000,
    ERRCODE_NOT_ENOUGH_BALANCE_SUB_VIRTUAL_PHONE: 400001,
    ERRCODE_NOT_ENOUGH_BALANCE_SUB_VIP: 400002,
    ERRCODE_SUB_VIRTUAL_PHONE_NEED_REFRESH: 400003,
    ERRCODE_NOT_SUB_VIRTUAL_PHONE: 400004,
    ERRCODE_CHANGE_SAME_PLAN: 400005,
    ERRCODE_NUMBER_ACTIVE: 400006,

    // code
    ERRCODE_NUMBER_DISABLED: 500001,

    // speech
    ERRCODE_INVITE_SPEECH_AUDIO_URL: 70000,
    ERRCODE_SPEECH_TO_TEXT_FAIL: 70001,
};

const ErrMsg = {
    ERRMSG_INTERNAL_ERROR: 'ERRMSG_INTERNAL_ERROR',
    // check in error
    ERRMSG_CHECK_IN_REPEAT: 'ERRMSG_CHECK_IN_REPEAT',
    ERRMSG_REQ_PARAM: 'ERRMSG_REQ_PARAM',
    ERRMSG_PATH_NOT_FOUND: 'ERRMSG_PATH_NOT_FOUND',
    ERRMSG_ILLEGAL_ACCESS: 'ERRMSG_ILLEGAL_ACCESS',
    ERRMSG_CAPTCHA_WRONG: 'ERRMSG_CAPTCHA_WRONG',
    ERRMSG_CAPTCHA_NEED: 'ERRMSG_CAPTCHA_NEED',
    ERRMSG_CALL_API_REPEAT: 'ERRMSG_CALL_API_REPEAT',
    ERRMSG_ILLEGAL_ACCESS_SIGN_DATE: 'ERRMSG_ILLEGAL_ACCESS_SIGN_DATE',

    // account error
    ERRMSG_ACCOUNT_DEACTIVATED: 'ERRMSG_ACCOUNT_DEACTIVATED',
    ERRMSG_CANCEL_MEMBERSHIP_FAILED: 'ERRMSG_CANCEL_MEMBERSHIP_FAILED',
    ERRMSG_RESTORE_MEMBERSHIP_FAILED: 'ERRMSG_RESTORE_MEMBERSHIP_FAILED',
    ERRMSG_ACCOUNT_NOT_MEMBERSHIP: 'ERRMSG_ACCOUNT_NOT_MEMBERSHIP',
    ERRMSG_ACCOUNT_BLOCKED: 'ERRMSG_ACCOUNT_BLOCKED',
    ERRMSG_NO_SUCH_ACCOUNT: 'ERRMSG_NO_SUCH_ACCOUNT',
    ERRMSG_ACCOUNT_NEED_LOGOUT: 'ERRMSG_ACCOUNT_NEED_LOGOUT',
    ERRMSG_PHONE_EXIST: 'ERRMSG_PHONE_EXIST',
    ERRMSG_PHONE_NOT_EXIST: 'ERRMSG_PHONE_NOT_EXIST',
    ERRMSG_INVITE_CODE_ERROR: 'ERRMSG_INVITE_CODE_ERROR',
    ERRMSG_SET_INVITE_CODE_FAILED: 'ERRMSG_SET_INVITE_CODE_FAILED',
    ERRMSG_SET_INVITE_CODE_FULL: 'ERRMSG_SET_INVITE_CODE_FULL',
    ERRMSG_SET_INVITE_CODE_DEVICE_DUP: 'ERRMSG_SET_INVITE_CODE_DEVICE_DUP',
    ERRMSG_INVITE_LOWEST_VERSION: 'ERRMSG_INVITE_LOWEST_VERSION',
    ERRMSG_ACCOUNT_HAVE_MEMBERSHIP: 'ERRMSG_ACCOUNT_HAVE_MEMBERSHIP',

    // set phone failed
    ERRMSG_SET_PHONE_FAILED: 'ERRMSG_SET_PHONE_FAILED',
    ERRMSG_SET_PHONE_FAILED_TIP: 'ERRMSG_SET_PHONE_FAILED_TIP',
    ERRMSG_CODE_ERROR: 'ERRMSG_CODE_ERROR',
    ERRMSG_MAX_TRIES: 'ERRMSG_MAX_TRIES',
    // call
    ERRMSG_CALL_INCORRECT_NUMBER: 'ERRMSG_CALL_INCORRECT_NUMBER',
    ERRMSG_NOT_SUPPORT_NUMBER: 'ERRMSG_NOT_SUPPORT_NUMBER',
    ERRMSG_VALIDATE_METHOD_SMS: 'ERRMSG_VALIDATE_METHOD_SMS',
    ERRMSG_CALL_NOT_ENOUGH_BALANCE: 'ERRMSG_CALL_NOT_ENOUGH_BALANCE',
    ERRMSG_SMS_NOT_SUPPORT_TOLLFREE: 'ERRMSG_SMS_NOT_SUPPORT_TOLLFREE',
    ERRMSG_SMS_SENT_LIMIT: 'ERRMSG_SMS_SENT_LIMIT',
    ERRMSG_SMS_INCORRECT_FROM_NUMBER: 'ERRMSG_SMS_INCORRECT_FROM_NUMBER',
    ERRMSG_SMS_INCORRECT_NUMBER: 'ERRMSG_SMS_INCORRECT_NUMBER',
    ERRMSG_SMS_ACCOUNT_LOG_OUT: 'ERRMSG_SMS_ACCOUNT_LOG_OUT',
    ERRMSG_SMS_SIMILAR_LIMIT2: 'ERRMSG_SMS_SIMILAR_LIMIT2',
    ERRMSG_SMS_SIMILAR_LIMIT: 'ERRMSG_SMS_SIMILAR_LIMIT',
    ERRMSG_SMS_NOT_SUPPORT_UK: 'ERRMSG_SMS_NOT_SUPPORT_UK',
    ERRMSG_SMS_SEND_FAILED: 'ERRMSG_SMS_SEND_FAILED',
    ERRMSG_SMS_TOLLFREE_NOT_OPENED: 'ERRMSG_SMS_TOLLFREE_NOT_OPENED',
    ERRMSG_CALL_INCORRECT_CHINA_NUMBER: 'ERRMSG_CALL_INCORRECT_CHINA_NUMBER',
    ERRMSG_CALL_CALLER_NUMBER_EXPIRED: 'ERRMSG_CALL_CALLER_NUMBER_EXPIRED',
    ERRMSG_CALL_HIGH_FREQ_LIMIT: 'ERRMSG_CALL_HIGH_FREQ_LIMIT',
    ERRMSG_CALL_NO_ANSWER_LIMIT: 'ERRMSG_CALL_NO_ANSWER_LIMIT',
    ERRMSG_CALL_HIGHRATE_BALANCE_NOT_ENOUGH: 'ERRMSG_CALL_HIGHRATE_BALANCE_NOT_ENOUGH',
    // sub
    ERRMSG_SUB_VIRTUAL_PHONE_FAILED_NEW: 'ERRMSG_SUB_VIRTUAL_PHONE_FAILED_NEW',
    ERRMSG_SUB_VIRTUAL_PHONE_NEED_REFRESH: 'ERRMSG_SUB_VIRTUAL_PHONE_NEED_REFRESH',
    ERRMSG_NOT_ENOUGH_BALANCE_SUB_VIRTUAL_PHONE: 'ERRMSG_NOT_ENOUGH_BALANCE_SUB_VIRTUAL_PHONE',
    ERRMSG_NOT_ENOUGH_BALANCE_SUB_VIP: 'ERRMSG_NOT_ENOUGH_BALANCE_SUB_VIP',
    ERRMSG_NOT_SUB_VIRTUAL_PHONE: 'ERRMSG_NOT_SUB_VIRTUAL_PHONE',
    ERRMSG_CHANGE_SAME_PLAN: 'ERRMSG_CHANGE_SAME_PLAN',
    ERRMSG_NUMBER_ACTIVE: 'ERRMSG_NUMBER_ACTIVE',
    ERRMSG_NOT_ENOUGH_BALANCE: 'ERRMSG_NOT_ENOUGH_BALANCE',

    // max bonus
    ERRMSG_MAX_BONUS_PER_DAY: 'ERRMSG_MAX_BONUS_PER_DAY',
    ERRMSG_MAX_BONUS_PER_HOUR: 'ERRMSG_MAX_BONUS_PER_HOUR',

    // ORDER ERROR
    ERRMSG_TRANSACTION_NOT_FOUND: 'ERRMSG_TRANSACTION_NOT_FOUND',
    ERRMSG_TRANSACTION_STATE_ALREADY: 'ERRMSG_TRANSACTION_STATE_ALREADY',
    ERRMSG_TRANSACTION_RECHARGE_ERROR: 'ERRMSG_TRANSACTION_RECHARGE_ERROR',
    ERRMSG_TRANSACTION_ALREADY_PROCESSED: 'ERRMSG_TRANSACTION_ALREADY_PROCESSED',
    ERRMSG_TRANSACTION_AVS_VERIFY_ERROR: 'ERRMSG_TRANSACTION_AVS_VERIFY_ERROR',
    ERRMSG_TRANSACTION_CVV2_VERIFY_ERROR: 'ERRMSG_TRANSACTION_CVV2_VERIFY_ERROR',
    ERRMSG_TRANSACTION_VERIFY_ERROR: 'ERRMSG_TRANSACTION_VERIFY_ERROR',

    // purchase
    // payment product not found in db
    ERRMSG_PRODUCT_NOT_FOUND: 'ERRMSG_PRODUCT_NOT_FOUND',

    // crypto
    ERRMSG_CRYPTO_PAY_SUBMIT_ERROR: 'ERRMSG_CRYPTO_PAY_SUBMIT_ERROR',

    // Recharge amount received not match with product amount in db.
    ERRMSG_RECHARGE_AMOUNT_NOT_MATCH: 'ERRMSG_RECHARGE_AMOUNT_NOT_MATCH',
    ERRMSG_PURCHASE_MAX_LIMIT: 'ERRMSG_PURCHASE_MAX_LIMIT',
    ERRMSG_PURCHASE_MAX_TIMES_LIMIT: 'ERRMSG_PURCHASE_MAX_TIMES_LIMIT',
    ERRMSG_PURCHASE_VALIDATE_FAILED: 'ERRMSG_PURCHASE_VALIDATE_FAILED',
    ERRMSG_PURCHASE_VALIDATE_UNKNOWN_ERROR: 'ERRMSG_PURCHASE_VALIDATE_UNKNOWN_ERROR',
    ERRMSG_PURCHASE_GOOGLE_48_LIMIT: 'ERRMSG_PURCHASE_GOOGLE_48_LIMIT',
    // speech
    ERRMSG_INVITE_SPEECH_AUDIO_URL: 'ERRMSG_INVITE_SPEECH_AUDIO_URL',
    ERRMSG_SPEECH_TO_TEXT_FAIL: 'ERRMSG_SPEECH_TO_TEXT_FAIL',

    // code
    ERRMSG_NUMBER_DISABLED: 'ERRMSG_NUMBER_DISABLED',
};

module.exports = {
    Exception,
    ErrCode,
    ErrMsg,

};
